version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: new-service:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - GNEWS_API_KEY=${GNEWS_API_KEY}
      - GNEWS_API_URL=https://gnews.io/api/v4
    restart: unless-stopped
